### ISSUE TITLE
Data API v3: POST /users, user can't sign in

### ISSUE THREAD

**Issue by nakedsushi** [movabletype/movabletype#368]
This is for MT version: `Movable Type version: r.4208 (7.0.1)`
When I create a new user through the v3 API with the correct systemPermissions:  `['sign_in_cms']`, the user is correctly created, but the user still can't log into the CMS because they get an "invalid login" error.  I can bypass this by going through the admin panel and re-saving the user OR manually updating the db table so that the `mt_author.author_auth_type = MT`, but this seems like a bug.

Steps to reproduce:
1. POST a request to /users to create a new user with the systemPermission to log into the cms: `sign_in_cms`
1. Try to sign in as that user and password to the CMS
1. BUG: user can't sign in to the CMS
1. Update the DB table: `update mt_author set author_auth_type='MT' where author_name='author_name_i_just-created';`
1. Try to sign in again with that created user , and now the user is able to sign in.

**Comment by miniuchi** [comment]
@nakedsushi 
Thank you for your comment. This is a bug.
We will fix this in future release.

**Comment by miniuchi** [comment]
@nakedsushi 

This bug has been fixed in #370 already and it will be released in future release.
But there is a workaround by creating plugin like the following.
https://gist.github.com/miniuchi/67bf3e2bee3369ecb92d631ab87f2959.

Please try it if you want to resolve the problem now.
Like https://github.com/movabletype/movabletype/issues/386#issuecomment-399814532, we do not guarantee it at all.

**Comment by nakedsushi** [comment]
Thank you!
