### ISSUE TITLE
mtapp:setting dynamic parameters fail

### ISSUE THREAD

**Issue by spagu** [movabletype/movabletype#46]
I am trying to add dynamic parameters to control template inside cms:

```
<mtapp:setting
                        id="<mt:var name="name" escape="html">"
                        label_class="top-label"
                        label="<mt:var name="label" escape="html">"
                        hint="<mt:var name="hint" escape="html">"
                        show_hint="<mt:var name="show_hint_custom" escape="html">">
                        <input id="name" type="text" name="<mt:var name="name" escape="html">" value="            <mt:var name="value" escape="html">" />
 </mtapp:setting>

```

variable show_hint_custom is passed to a template with a correct state ( 1 or 0 ) 
app:setting is setting always 1 for variable even variable has 0
the same thing is happening to required attribute.

is it bug? or there is workaround?

**Comment by yuji** [comment]
hm... Can I get your plugin for investigate?

**Comment by dphillips** [comment]
This entire block of code is one template tag:
```
<mtapp:setting
                        id="<mt:var name="name" escape="html">"
                        label_class="top-label"
                        label="<mt:var name="label" escape="html">"
                        hint="<mt:var name="hint" escape="html">"
                        show_hint="<mt:var name="show_hint_custom" escape="html">">
```
At least part of the reason why this issue is occurring is that you cannot have template tags nested within a template tag as above. Instead of using template tags to reference Movable Type variables, you must use Movable Type's [variable interpolation](https://movabletype.org/documentation/designer/variable-interpolation.html):
```
<mtapp:setting
                        id="$name"
                        label_class="top-label"
                        label="$label"
                        hint="$hint"
                        show_hint="$show_hint_custom">
```
If you need the variable values to be html-escaped, you would need to add template code to do this to each variable and resave the value before executing the above template code.

**Comment by charsbar** [comment]
Closing.
